spring:
  application:
    name: blogbackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_Blog
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      database: 0
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true


#阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: anonce1
    region: cn-beijing


#spring事务管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
